# Generated by Django 5.2.5 on 2025-09-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackIDE", "0010_problem_company_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestAttachedProblem",
            fields=[],
            options={
                "verbose_name": "Contest Problem",
                "verbose_name_plural": "Contest Problems",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("hackIDE.contestproblem",),
        ),
        migrations.CreateModel(
            name="StandaloneProblem",
            fields=[],
            options={
                "verbose_name": "Standalone Problem",
                "verbose_name_plural": "Standalone Problems",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("hackIDE.contestproblem",),
        ),
        migrations.AlterField(
            model_name="contest",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="contestparticipant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="contestproblem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="contestsubmission",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="proctoringsession",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
