# Generated by Django 5.2.5 on 2025-09-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackIDE", "0011_contestattachedproblem_standaloneproblem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="first_prize",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="contest",
            name="second_prize",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="contest",
            name="third_prize",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
