# Generated by Django 5.2.5 on 2025-09-05 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackIDE", "0013_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="proctoringsession",
            name="contest_terminated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proctoringsession",
            name="is_monitoring_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proctoringsession",
            name="last_face_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proctoringsession",
            name="monitoring_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proctoringsession",
            name="violation_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="proctoringsession",
            name="warning_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ProctoringViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("FACE_NOT_DETECTED", "Face Not Detected"),
                            ("MULTIPLE_FACES", "Multiple Faces Detected"),
                            ("CAMERA_BLOCKED", "Camera Blocked"),
                            ("NO_CAMERA_ACCESS", "No Camera Access"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("warning_given", models.BooleanField(default=False)),
                (
                    "proctoring_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="hackIDE.proctoringsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
