# Generated by Django 5.2.5 on 2025-09-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackIDE", "0014_proctoringsession_contest_terminated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestsubmission",
            name="is_final_submission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contestsubmission",
            name="submission_type",
            field=models.CharField(
                choices=[("TEST", "Test Submission"), ("FINAL", "Final Submission")],
                default="TEST",
                max_length=20,
            ),
        ),
    ]
