# Generated by Django 5.2.5 on 2025-09-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackIDE", "0015_contestsubmission_is_final_submission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipant",
            name="final_submission_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="contestparticipant",
            name="final_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestparticipant",
            name="has_final_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
