# Generated by Django 5.2.5 on 2025-09-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackIDE", "0016_add_contest_final_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="requires_proctoring",
            field=models.BooleanField(
                default=True,
                help_text="Enable camera verification and monitoring for this contest",
            ),
        ),
    ]
