# Generated by Django 5.2.5 on 2025-09-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackIDE", "0017_contest_requires_proctoring"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestsubmission",
            name="is_practice_submission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proctoringsession",
            name="practice_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contestsubmission",
            name="submission_type",
            field=models.CharField(
                choices=[
                    ("TEST", "Test Submission"),
                    ("FINAL", "Final Submission"),
                    ("PRACTICE", "Practice Submission"),
                ],
                default="TEST",
                max_length=20,
            ),
        ),
    ]
